### ISSUE TITLE
Suggestion: separate item_count into conversation_count and event_count

### ISSUE THREAD

**Issue by allanw** [microcosm-cc/microcosm#2]
On a site's homepage, each Microcosm is listed with the value for item_count alongside it. Currently, item_count is rendered as e.g. "n conversations". This is slightly misleading, as the count includes both conversations and events.

Separating this count into two different variables would allow the conversation and event counts to be rendered separately on the front-end.

**Comment by buro9** [comment]
It's called item_count as it is a count of items within a microcosm.

I didn't break it out into constituent parts as all the types of item is extensible and polls were mostly done when the company failed, we already had conversations and events, and in the pipeline were: Q&A, surveys, classified adverts, blog posts, articles, photo albums, etc.

It would be a UX nightmare to have each type declare it's own number, as well as restricting the code so that any new type that was added would now require code changes throughout the codebase.

This is also why, when querying a microcosm itself, you don't get the split of types... it's just not that important.

The closest competitor to this concept is Tumblr, and you should note that even they don't report on quantities of types anywhere in their API: https://www.tumblr.com/docs/en/api/v2#posts . You either get a "blog" (their container for types of content) which just tells you the sum of all posts to the blog: https://www.tumblr.com/docs/en/api/v2#blog-info and that doesn't clarify the count of each type, or you get the posts themselves... but that doesn't break out the sum of each type either.
